"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { ensureActiveUser } from "@/lib/supabase/auth-client";
import SideNav from "@/components/side-nav";

type ExpenseRow = { amount: number; expense_date: string };
type IncomeRow = { amount: number; income_date: string };
type InvestmentRow = { quantity: number; average_buy_price: number; current_price: number | null };

type DashboardMetrics = {
  totalNetWorth: number;
  savingsRate: number | null;
  fireTarget: number;
  fireProgress: number;
  yearsToFire: number | null;
  annualExpenses: number;
  annualSavings: number;
};

function isSameMonth(dateString: string, now: Date) {
  const date = new Date(`${dateString}T00:00:00`);
  return date.getFullYear() === now.getFullYear() && date.getMonth() === now.getMonth();
}

function isWithinLast12Months(dateString: string, now: Date) {
  const date = new Date(`${dateString}T00:00:00`);
  const cutoff = new Date(now.getFullYear(), now.getMonth(), 1);
  cutoff.setMonth(cutoff.getMonth() - 11);
  return date >= cutoff;
}

function estimateYearsToFire(current: number, target: number, annualContribution: number, expectedReturn = 0.05) {
  if (current >= target) return 0;
  if (annualContribution <= 0) return null;

  let value = current;
  const maxYears = 100;

  for (let year = 1; year <= maxYears; year++) {
    value = value * (1 + expectedReturn) + annualContribution;
    if (value >= target) {
      return year;
    }
  }

  return null;
}

export default function DashboardPage() {
  const supabase = useMemo(() => createClient(), []);

  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState<string | null>(null);
  const [metrics, setMetrics] = useState<DashboardMetrics | null>(null);

  const [aiLoading, setAiLoading] = useState(false);
  const [aiError, setAiError] = useState<string | null>(null);
  const [aiSource, setAiSource] = useState<string | null>(null);
  const [aiInsights, setAiInsights] = useState<string[]>([]);
  const [aiAutoGenerated, setAiAutoGenerated] = useState(false);

  const hasFinancialData = Boolean(
    metrics && (metrics.totalNetWorth > 0 || metrics.annualExpenses > 0 || metrics.annualSavings !== 0)
  );

  const generateInsights = useCallback(async () => {
    setAiLoading(true);
    setAiError(null);

    try {
      const response = await fetch("/api/ai-insights", { method: "POST" });
      if (!response.ok) {
        setAiError("No se pudieron generar insights en este momento.");
        setAiLoading(false);
        return;
      }

      const data = (await response.json()) as { source?: string; insights?: string[] };
      setAiSource(data.source ?? "unknown");
      setAiInsights(Array.isArray(data.insights) ? data.insights : []);
      setAiLoading(false);
    } catch {
      setAiError("Error de red al generar insights.");
      setAiLoading(false);
    }
  }, []);

  useEffect(() => {
    const run = async () => {
      setLoading(true);
      setMessage(null);

      const activeUser = await ensureActiveUser(supabase);
      if (!activeUser) {
        setMessage("No hay sesion activa. Inicia sesion para ver el dashboard.");
        setLoading(false);
        return;
      }

      const userId = activeUser.id;

      const [{ data: expenses, error: expensesError }, { data: income, error: incomeError }, { data: investments, error: invError }] =
        await Promise.all([
          supabase.from("expenses").select("amount, expense_date").eq("user_id", userId),
          supabase.from("income").select("amount, income_date").eq("user_id", userId),
          supabase.from("investments").select("quantity, average_buy_price, current_price").eq("user_id", userId)
        ]);

      if (expensesError || incomeError || invError) {
        setMessage(expensesError?.message || incomeError?.message || invError?.message || "Error al cargar datos.");
        setLoading(false);
        return;
      }

      const now = new Date();
      const expenseRows = (expenses as ExpenseRow[]) ?? [];
      const incomeRows = (income as IncomeRow[]) ?? [];
      const investmentRows = (investments as InvestmentRow[]) ?? [];

      const totalNetWorth = investmentRows.reduce((acc, row) => {
        const qty = Number(row.quantity) || 0;
        const price = Number(row.current_price ?? row.average_buy_price) || 0;
        return acc + qty * price;
      }, 0);

      const monthExpenses = expenseRows.reduce((acc, row) => (isSameMonth(row.expense_date, now) ? acc + Number(row.amount) : acc), 0);
      const monthIncome = incomeRows.reduce((acc, row) => (isSameMonth(row.income_date, now) ? acc + Number(row.amount) : acc), 0);
      const savingsRate = monthIncome > 0 ? ((monthIncome - monthExpenses) / monthIncome) * 100 : null;

      const annualExpenses = expenseRows.reduce(
        (acc, row) => (isWithinLast12Months(row.expense_date, now) ? acc + Number(row.amount) : acc),
        0
      );
      const annualIncome = incomeRows.reduce(
        (acc, row) => (isWithinLast12Months(row.income_date, now) ? acc + Number(row.amount) : acc),
        0
      );
      const annualSavings = annualIncome - annualExpenses;

      const fireTarget = annualExpenses > 0 ? annualExpenses / 0.04 : 0;
      const fireProgress = fireTarget > 0 ? Math.min((totalNetWorth / fireTarget) * 100, 100) : 0;
      const yearsToFire = fireTarget > 0 ? estimateYearsToFire(totalNetWorth, fireTarget, Math.max(annualSavings, 0), 0.05) : null;

      setMetrics({
        totalNetWorth,
        savingsRate,
        fireTarget,
        fireProgress,
        yearsToFire,
        annualExpenses,
        annualSavings
      });
      setLoading(false);
    };

    void run();
  }, [supabase]);

  useEffect(() => {
    if (!loading && !message && metrics && !aiAutoGenerated && hasFinancialData) {
      setAiAutoGenerated(true);
      void generateInsights();
    }
  }, [loading, message, metrics, aiAutoGenerated, generateInsights, hasFinancialData]);

  return (
    <>
      <SideNav />
      <main className="mx-auto grid max-w-6xl gap-6 p-6 md:pl-60 md:grid-cols-2">
      <section className="rounded-lg border bg-white p-4">
        <h1 className="mb-4 text-2xl font-semibold">Dashboard financiero</h1>
        <p className="text-sm text-slate-600">Resumen automatico con datos de ingresos, gastos e inversiones.</p>
      </section>

      {loading ? (
        <section className="rounded-lg border bg-white p-4 md:col-span-2">
          <p>Cargando metricas...</p>
        </section>
      ) : null}

      {message ? (
        <section className="rounded-lg border bg-white p-4 md:col-span-2">
          <p className="text-red-700">{message}</p>
        </section>
      ) : null}

      {!loading && !message && metrics ? (
        <>
          {!hasFinancialData ? (
            <section className="rounded-lg border bg-amber-50 p-4 text-amber-800 md:col-span-2">
              Aun no hay datos suficientes para analisis completo. Anade ingresos, gastos o inversiones para activar todas las metricas.
            </section>
          ) : null}

          <section className="rounded-lg border bg-white p-4">
            <h2 className="mb-2 text-lg font-semibold">Patrimonio total</h2>
            <p className="text-2xl font-bold">{metrics.totalNetWorth.toFixed(2)} EUR</p>
          </section>

          <section className="rounded-lg border bg-white p-4">
            <h2 className="mb-2 text-lg font-semibold">Tasa de ahorro (mes actual)</h2>
            <p className="text-2xl font-bold">
              {metrics.savingsRate === null ? "Sin datos de ingresos" : `${metrics.savingsRate.toFixed(2)}%`}
            </p>
          </section>

          <section className="rounded-lg border bg-white p-4 md:col-span-2">
            <h2 className="mb-3 text-lg font-semibold">Progreso hacia libertad financiera</h2>
            <div className="mb-2 h-4 w-full rounded bg-slate-200">
              <div className="h-4 rounded bg-teal-600" style={{ width: `${metrics.fireProgress.toFixed(2)}%` }} />
            </div>
            <p className="text-sm">
              {metrics.fireProgress.toFixed(2)}% completado
              {metrics.fireTarget > 0 ? ` (objetivo FIRE: ${metrics.fireTarget.toFixed(2)} EUR)` : ""}
            </p>
          </section>

          <section className="rounded-lg border bg-white p-4 md:col-span-2">
            <h2 className="mb-2 text-lg font-semibold">Anos estimados para independencia</h2>
            <p className="text-2xl font-bold">
              {metrics.fireTarget <= 0
                ? "No calculable (faltan gastos anuales)"
                : metrics.yearsToFire === null
                  ? "No alcanzable con el ahorro actual"
                  : `${metrics.yearsToFire} anos`}
            </p>
            <p className="mt-2 text-sm text-slate-600">
              Supuestos: regla del 4%, ahorro anual reciente y rentabilidad esperada del 5%.
            </p>
            <p className="mt-1 text-sm text-slate-600">Ahorro anual estimado: {metrics.annualSavings.toFixed(2)} EUR.</p>
          </section>

          <section className="rounded-lg border bg-white p-4 md:col-span-2">
            <div className="mb-3 flex items-center justify-between">
              <h2 className="text-lg font-semibold">IA financiera</h2>
              <button
                className="rounded bg-indigo-700 px-3 py-2 text-sm text-white disabled:opacity-50"
                onClick={generateInsights}
                disabled={aiLoading || !hasFinancialData}
                type="button"
              >
                {aiLoading ? "Analizando..." : "Regenerar insights IA"}
              </button>
            </div>

            {!hasFinancialData ? (
              <p className="text-sm text-slate-600">Sin datos financieros suficientes para generar insights utiles.</p>
            ) : null}
            {aiError ? <p className="text-sm text-red-700">{aiError}</p> : null}
            {!aiError && aiInsights.length === 0 && hasFinancialData ? (
              <p className="text-sm text-slate-600">Generando recomendaciones personalizadas...</p>
            ) : null}

            {aiInsights.length > 0 ? (
              <>
                <ul className="ml-5 list-disc text-sm">
                  {aiInsights.map((insight) => (
                    <li key={insight}>{insight}</li>
                  ))}
                </ul>
                <p className="mt-3 text-xs text-slate-500">
                  Fuente: {aiSource === "openai" ? "modelo OpenAI" : "motor local de reglas"}. No es consejo financiero profesional.
                </p>
              </>
            ) : null}
          </section>
        </>
      ) : null}
      </main>
    </>
  );
}

